### ISSUE TITLE
Typo in README!

### ISSUE THREAD

**Issue by k0ns0l** [Mopheshi/BusTicketingSystem#1]
Update highlighted typo in the `Getting-started` for README section - [ Steps to clone repository ]
```bash
git clone https://github.com/Mopheshi/BusTicketingSystem.git
```

**Comment by Mopheshi** [comment]
Thank you for your observation, boss.
I will soon be archiving the repo once work gets serious.
This is a temporary repo, just to share the code as suggested by the course
lecturer.

**Comment by k0ns0l** [comment]
*LFG!*
